data={'biglist': ["A",
"A\'s",
"AA\'s",
"AB\'s",
"ABM\'s",
"AC\'s",
"ACTH\'s",
"AI\'s",
"AIDS\'s",
"AM\'s",
"AOL",
"AOL\'s",
"ASCII\'s",
"ASL\'s",
"ATM\'s",
"ATP\'s",
"AWOL\'s",
"AZ\'s",
"AZT\'s",
"Aachen",
"Aaliyah",
"Aaliyah\'s",
"Aaron",
"Abbas",
"Abbasid",
"Abbott",
"Abbott\'s",
"Abby",
"Abby\'s",
"Abdul",
"Abdul\'s",
"Abe",
"Abe\'s",
"Abel",
"Abel\'s",
"Abelard",
"Abelson",
"Abelson\'s",
"Aberdeen",
"Aberdeen\'s",
"Abernathy",
"Abernathy\'s",
"Abidjan",
"Abidjan\'s",
"Abigail",
"Abilene",
"Abner",
"Abner\'s",
"Abraham",
"Abraham\'s",
"Abram",
"Abram\'s",
"Abrams",
"Absalom",
"Abuja",
"Abyssinia",
"Abyssinia\'s",
"Abyssinian",
"Abyssinian\'s",
"Ac",
"Ac\'s",
"Acadia",
"Acadia\'s",
"Acapulco",
"Acapulco\'s",
"Accenture",
"Accenture\'s",
"Accra",
"Accra\'s",
"Acevedo",
"Acevedo\'s",
"Achaean",
"Achaean\'s",
"Achebe",
"Achebe\'s",
"Achernar",
"Acheson",
"Acheson\'s",
"Achilles",
"Achilles\'s",
"Aconcagua",
"Aconcagua\'s",
"Acosta",
"Acosta\'s",
"Acropolis",
"Acrux",
"Acrux\'s",
"Actaeon",
"Acton",
"Acts",
"Acuff",
"Acuff\'s",
"Ada",
"Ada\'s",
"Adam",
"Adam\'s",
"Adams",
"Adan",
"Adan\'s",
"Adana",
"Adar",
"Adar\'s",
"Addams",
"Adderley",
"Adderley\'s",
"Addie",
"Addie\'s",
"Addison",
"Adela",
"Adela\'s",
"Adelaide",
"Adelaide\'s",
"Adele",
"Adele\'s",
"Adeline",
"Adeline\'s",
"Aden",
"Aden\'s",
"Adenauer",
"Adhara",
"Adhara\'s",
"Adidas",
"Adidas\'s",
"Adirondack",
"Adirondack\'s",
"Adirondacks",
"Adirondacks\'s",
"Adkins",
"Adkins\'s",
"Adler",
"Adolf",
"Adolf\'s",
"Adolfo",
"Adolfo\'s",
"Adolph",
"Adolph\'s",
"Adonis",
"Adonis\'s",
"Adonises",
"Adrian",
"Adriana",
"Adriana\'s",
"Adriatic",
"Adriatic\'s",
"Adrienne",
"Adrienne\'s",
"Advent",
"Advent\'s",
"Adventist",
"Adventist\'s",
"Advents",
"Advil",
"Advil\'s",
"Aegean",
"Aegean\'s",
"Aelfric",
"Aelfric\'s",
"Aeneas",
"Aeneas\'s",
"Aeneid",
"Aeneid\'s",
"Aeolus",
"Aeolus\'s",
"Aeroflot",
"Aeroflot\'s",
"Aeschylus",
"Aeschylus\'s",
"Aesculapius",
"Aesculapius\'s",
"Aesop",
"Aesop\'s",
"Afghan",
"Afghan\'s",
"Afghanistan",
"Afghanistan\'s",
"Afghans",
"Africa",
"Africa\'s",
"African",
"African\'s",
"Africans",
"Afrikaans",
"Afrikaans\'s",
"Afrikaner",
"Afrikaner\'s",
"Afrikaners",
"Afro",
"Afro\'s",
"Afrocentrism",
"Afros",
"Ag",
"Ag\'s",
"Agamemnon",
"Agamemnon\'s",
"Agassi",
"Agassi\'s",
"Agassiz",
"Agassiz\'s",
"Agatha",
"Agatha\'s",
"Aggie",
"Aglaia",
"Agnes",
"Agnew",
"Agnew\'s",
"Agni",
"Agni\'s",
"Agra",
"Agricola",
"Agrippa",
"Agrippa\'s",
"Agrippina",
"Agrippina\'s",
"Aguilar",
"Aguilar\'s",
"Aguinaldo",
"Aguinaldo\'s",
"Aguirre",
"Aguirre\'s",
"Agustin",
"Agustin\'s",
"Ahab",
"Ahab\'s",
"Ahmad",
"Ahmad\'s",
"Ahmadabad",
"Ahmadinejad",
"Ahmadinejad\'s",
"Ahmed",
"Ahmed\'s",
"Ahriman",
"Ahriman\'s",
"Aida",
"Aida\'s",
"Aiken",
"Aileen",
"Aileen\'s",
"Aimee",
"Aimee\'s",
"Ainu",
"Airedale",
"Airedale\'s",
"Airedales",
"Aisha",
"Ajax",
"Ajax\'s",
"Akbar",
"Akhmatova",
"Akhmatova\'s",
"Akihito",
"Akita",
"Akiva",
"Akiva\'s",
"Akkad",
"Akron",
"Akron\'s",
"Al",
"Al\'s",
"Ala",
"Alabama",
"Alabama\'s",
"Alabaman",
"Alabaman\'s",
"Alabamans",
"Alabamian",
"Alabamian\'s",
"Alabamians",
"Aladdin",
"Aladdin\'s",
"Alamo",
"Alamo\'s",
"Alamogordo",
"Alamogordo\'s",
"Alan",
"Alan\'s",
"Alana",
"Alana\'s",
"Alar",
"Alar\'s",
"Alaric",
"Alaska",
"Alaska\'s",
"Alaskan",
"Alaskan\'s",
"Alaskans",
"Alba",
"Albania",
"Albania\'s",
"Albanian",
"Albanian\'s",
"Albanians",
"Albany",
"Albany\'s",
"Albee",
"Alberio",
"Alberio\'s",
"Albert",
"Alberta",
"Alberta\'s",
"Alberto",
"Alberto\'s",
"Albigensian",
"Albion",
"Albireo",
"Albireo\'s",
"Albuquerque",
"Albuquerque\'s",
"Alcatraz",
"Alcestis",
"Alcibiades",
"Alcindor",
"Alcindor\'s",
"Alcmena",
"Alcmena\'s",
"Alcoa",
"Alcoa\'s",
"Alcott",
"Alcuin",
"Alcyone",
"Aldan",
"Aldebaran",
"Aldebaran\'s",
"Alden",
"Alderamin",
"Alderamin\'s",
"Aldo",
"Aldo\'s",
"Aldrin",
"Aldrin\'s",
"Alec",
"Alec\'s",
"Aleichem",
"Aleichem\'s",
"Alejandra",
"Alejandra\'s",
"Alejandro",
"Alejandro\'s",
"Alembert",
"Alembert\'s",
"Aleppo",
"Aleppo\'s",
"Aleut",
"Aleut\'s",
"Aleutian",
"Aleutian\'s",
"Alex",
"Alex\'s",
"Alexander",
"Alexander\'s",
"Alexandra",
"Alexandria",
"Alexandria\'s",
"Alexei",
"Alexei\'s",
"Alexis",
"Alfonso",
"Alfonso\'s",
"Alfonzo",
"Alfonzo\'s",
"Alford",
"Alford\'s",
"Alfred",
"Alfreda",
"Alfreda\'s",
"Alfredo",
"Algenib",
"Algenib\'s",
"Alger",
"Algeria",
"Algeria\'s",
"Algerian",
"Algerian\'s",
"Algerians",
"Algieba",
"Algieba\'s",
"Algiers",
"Algiers\'s",
"Algol",
"Algol\'s",
"Algonquian",
"Algonquian\'s",
"Algonquians",
"Algonquin",
"Algonquin\'s",
"Alhambra",
"Alhena",
"Alhena\'s",
"Ali",
"Alice",
"Alice\'s",
"Alicia",
"Alicia\'s",
"Alighieri",
"Alighieri\'s",
"Aline",
"Aline\'s",
"Alioth",
"Alioth\'s",
"Alisa",
"Alisa\'s",
"Alisha",
"Alisha\'s",
"Alison",
"Alison\'s",
"Alissa",
"Alissa\'s",
"Alistair",
"Alistair\'s",
"Alkaid",
"Alkaid\'s",
"Allah",
"Allah\'s",
"Allahabad",
"Allan",
"Allan\'s",
"Alleghenies",
"Alleghenies\'s",
"Allegheny",
"Allegra",
"Allegra\'s",
"Allen",
"Allende",
"Allende\'s",
"Allentown",
"Allie",
"Allie\'s",
"Allison",
"Allison\'s",
"Allstate",
"Allstate\'s",
"Allyson",
"Allyson\'s",
"Alma",
"Alma\'s",
"Almach",
"Almach\'s",
"Almaty",
"Almaty\'s",
"Almighty",
"Almighty\'s",
"Almohad",
"Almohad\'s",
"Almoravid",
"Almoravid\'s",
"Alnilam",
"Alnilam\'s",
"Alnitak",
"Alnitak\'s",
"Alonzo",
"Alonzo\'s",
"Alpert",
"Alpert\'s",
"Alphard",
"Alphard\'s",
"Alphecca",
"Alphecca\'s",
"Alpheratz",
"Alpheratz\'s",
"Alphonse",
"Alphonse\'s",
"Alphonso",
"Alphonso\'s",
"Alpine",
"Alpo",
"Alpo\'s",
"Alps",
"Alps\'s",
"Alsace",
"Alsace\'s",
"Alsatian",
"Alsatian\'s",
"Alsop",
"Alsop\'s",
"Alston",
"Alston\'s",
"Alta",
"Altai",
"Altai\'s",
"Altaic",
"Altaic\'s",
"Altair",
"Altamira",
"Althea",
"Althea\'s",
"Altiplano",
"Altiplano\'s",
"Altman",
"Altman\'s",
"Altoids",
"Altoids\'s",
"Alton",
"Alton\'s",
"Aludra",
"Aludra\'s",
"Alva",
"Alvarado",
"Alvarado\'s",
"Alvarez",
"Alvarez\'s",
"Alvaro",
"Alvaro\'s",
"Alvin",
"Alvin\'s",
"Alyce",
"Alyce\'s",
"Alyson",
"Alyson\'s",
"Alyssa",
"Alyssa\'s",
"Alzheimer",
"Alzheimer\'s",
"Am",
"Am\'s",
"Amadeus",
"Amadeus\'s",
"Amado",
"Amado\'s",
"Amalia",
"Amalia\'s",
"Amanda",
"Amanda\'s",
"Amarillo",
"Amaru",
"Amaru\'s",
"Amaterasu",
"Amaterasu\'s",
"Amati",
"Amazon",
"Amazon\'s",
"Amazons",
"Amber",
"Amber\'s",
"Amelia",
"Amelia\'s",
"Amenhotep",
"Amenhotep\'s",
"Amerasian",
"America",
"America\'s",
"American",
"American\'s",
"Americana",
"Americana\'s",
"Americanism",
"Americanism\'s",
"Americanisms",
"Americanization",
"Americanization\'s",
"Americanizations",
"Americanize",
"Americanized",
"Americanizes",
"Americanizing",
"Americans",
"Americas",
"Amerind",
"Amerind\'s",
"Amerindian",
"Amerindian\'s",
"Amerindians",
"Amerinds",
"Ameslan",
"Ameslan\'s",
"Amharic",
"Amharic\'s",
"Amherst",
"Amie",
"Amie\'s",
"Amiga",
"Amiga\'s",
"Amish",
"Amish\'s",
"Amman",
"Amman\'s",
"Amoco",
"Amoco\'s",
"Amos",
"Amparo",
"Amparo\'s",
"Ampere",
"Ampere\'s",
"Amritsar",
"Amsterdam",
"Amsterdam\'s",
"Amtrak",
"Amundsen",
"Amur",
"Amur\'s",
"Amway",
"Amway\'s",
"Amy",
"Amy\'s",
"Ana",
"Ana\'s",
"Anabaptist",
"Anabaptist\'s",
"Anabel",
"Anabel\'s",
"Anacin",
"Anacin\'s",
"Anacreon",
"Anaheim",
"Analects",
"Analects\'s",
"Ananias",
"Ananias\'s",
"Anasazi",
"Anastasia",
"Anatole",
"Anatole\'s",
"Anatolia",
"Anatolia\'s",
"Anatolian",
"Anatolian\'s",
"Anaxagoras",
"Anchorage",
"Anchorage\'s",
"Andalusia",
"Andalusia\'s",
"Andalusian",
"Andaman",
"Andean",
"Andersen",
"Andersen\'s",
"Anderson",
"Andes",
"Andes\'s",
"Andorra",
"Andorra\'s",
"Andre",
"Andre\'s",
"Andrea",
"Andrea\'s",
"Andrei",
"Andrei\'s",
"Andres",
"Andretti",
"Andretti\'s",
"Andrew",
"Andrew\'s",
"Andrews",
"Andrianampoinimerina",
"Andrianampoinimerina\'s",
"Android",
"Android\'s",
"Andromache",
"Andromeda",
"Andromeda\'s",
"Andropov",
"Andy",
"Andy\'s",
"Angara",
"Angel",
"Angel\'s",
"Angela",
"Angela\'s",
"Angelia",
"Angelia\'s",
"Angelica",
"Angelico",
"Angelina",
"Angelina\'s",
"Angeline",
"Angeline\'s",
"Angelique",
"Angelique\'s",
"Angelita",
"Angelita\'s",
"Angelo",
"Angelo\'s",
"Angelou",
"Angevin",
"Angevin\'s",
"Angie",
"Angie\'s",
"Angkor",
"Anglia",
"Anglican",
"Anglican\'s",
"Anglicanism",
"Anglicanism\'s",
"Anglicanisms",
"Anglicans",
"Anglicize",
"Anglo",
"Anglophile",
"Angola",
"Angola\'s",
"Angolan",
"Angolan\'s",
"Angolans",
"Angora",
"Angora\'s",
"Angoras",
"Anguilla",
"Anguilla\'s",
"Angus",
"Angus\'s",
"Aniakchak",
"Aniakchak\'s",
"Anibal",
"Anibal\'s",
"Anita",
"Anita\'s",
"Ankara",
"Ankara\'s",
"Ann",
"Ann\'s",
"Anna",
"Annabel",
"Annabel\'s",
"Annabelle",
"Annabelle\'s",
"Annam",
"Annam\'s",
"Annapolis",
"Annapolis\'s",
"Annapurna",
"Annapurna\'s",
"Anne",
"Annette",
"Annette\'s",
"Annie",
"Annie\'s",
"Annmarie",
"Annmarie\'s",
"Anouilh",
"Anselm",
"Anselmo",
"Anselmo\'s",
"Anshan",
"Anshan\'s",
"Antaeus",
"Antananarivo",
"Antananarivo\'s",
"Antarctic",
"Antarctic\'s",
"Antarctica",
"Antarctica\'s",
"Antares",
"Antares\'s",
"Anthony",
"Antichrist",
"Antichrist\'s",
"Antichrists",
"Antietam",
"Antigone",
"Antigone\'s",
"Antigua",
"Antigua\'s",
"Antilles",
"Antilles\'s",
"Antioch",
"Antipas",
"Antipas\'s",
"Antofagasta",
"Antofagasta\'s",
"Antoine",
"Antoine\'s",
"Antoinette",
"Anton",
"Anton\'s",
"Antone",
"Antone\'s",
"Antonia",
"Antonia\'s",
"Antoninus",
"Antonio",
"Antonio\'s",
"Antonius",
"Antony",
"Antony\'s",
"Antwan",
"Antwan\'s",
"Antwerp",
"Antwerp\'s",
"Anubis",
"Anubis\'s",
"Anzac",
"Apache",
"Apache\'s",
"Apaches",
"Apalachicola",
"Apalachicola\'s",
"Apennines",
"Aphrodite",
"Aphrodite\'s",
"Apia",
"Apocrypha",
"Apocrypha\'s",
"Apollinaire",
"Apollo",
"Apollo\'s",
"Apollonian",
"Apollos",
"Appalachia",
"Appalachia\'s",
"Appalachian",
"Appalachians",
"Appaloosa",
"Appaloosa\'s",
"Apple",
"Apple\'s",
"Appleseed",
"Appleton",
"Appomattox",
"Apr",
"Apr\'s",
"April",
"April\'s",
"Aprils",
"Apuleius",
"Aquafresh",
"Aquafresh\'s",
"Aquarius",
"Aquarius\'s",
"Aquariuses",
"Aquila",
"Aquinas",
"Aquinas\'s",
"Aquino",
"Aquino\'s",
"Aquitaine",
"Aquitaine\'s",
"Ar",
"Ar\'s",
"Ara",
"Ara\'s",
"Arab",
"Arab\'s",
"Arabia",
"Arabia\'s",
"Arabian",
"Arabian\'s",
"Arabians",
"Arabic",
"Arabic\'s",
"Arabs",
"Araby",
"Araceli",
"Araceli\'s",
"Arafat",
"Arafat\'s",
"Araguaya",
"Araguaya\'s",
"Aral",
"Aral\'s",
"Aramaic",
"Aramaic\'s",
"Aramco",
"Aramco\'s",
"Arapaho",
"Arapaho\'s",
"Ararat",
"Ararat\'s",
"Araucanian",
"Arawak",
"Arawak\'s",
"Arawakan",
"Arawakan\'s",
"Arbitron",
"Arbitron\'s",
"Arcadia",
"Arcadia\'s",
"Arcadian",
"Arcadian\'s",
"Archean",
"Archibald",
"Archibald\'s",
"Archie",
"Archie\'s",
"Archimedes",
"Arctic",
"Arctic\'s",
"Arcturus",
"Arcturus\'s",
"Arden",
"Arequipa",
"Ares",
"Argentina",
"Argentina\'s",
"Argentine",
"Argentinian",
"Argentinian\'s",
"Argentinians",
"Argo",
"Argonaut",
"Argonaut\'s",
"Argonne",
"Argonne\'s",
"Argos",
"Argus",
"Argus\'s",
"Ariadne",
"Ariadne\'s",
"Arianism",
"Arianism\'s",
"Ariel",
"Aries",
"Aries\'s",
"Arieses",
"Ariosto",
"Aristarchus",
"Aristarchus\'s",
"Aristides",
"Aristophanes",
"Aristophanes\'s",
"Aristotelian",
"Aristotelian\'s",
"Aristotle",
"Aristotle\'s",
"Arius",
"Arius\'s",
"Ariz",
"Arizona",
"Arizona\'s",
"Arizonan",
"Arizonan\'s",
"Arizonans",
"Arizonian",
"Arizonian\'s",
"Arizonians",
"Arjuna",
"Ark",
"Arkansan",
"Arkansan\'s",
"Arkansas",
"Arkansas\'s",
"Arkhangelsk",
"Arkwright",
"Arlene",
"Arlene\'s",
"Arline",
"Arline\'s",
"Arlington",
"Armageddon",
"Armageddon\'s",
"Armageddons",
"Armagnac",
"Armagnac\'s",
"Armand",
"Armand\'s",
"Armando",
"Armando\'s",
"Armani",
"Armani\'s",
"Armenia",
"Armenia\'s",
"Armenian",
"Armenian\'s",
"Armenians",
"Arminius",
"Arminius\'s",
"Armonk",
"Armonk\'s",
"Armour",
"Armour\'s",
"Armstrong",
"Armstrong\'s",
"Arneb",
"Arneb\'s",
"Arnhem",
"Arno",
"Arno\'s",
"Arnold",
"Arnulfo",
"Arnulfo\'s",
"Aron",
"Aron\'s",
"Arrhenius",
"Arron",
"Arron\'s",
"Art",
"Art\'s",
"Artaxerxes",
"Artaxerxes\'s",
"Artemis",
"Artemis\'s",
"Arthur",
"Arthur\'s",
"Arthurian",
"Artie",
"Artie\'s",
"Arturo",
"Arturo\'s",
"Aruba",
"Aruba\'s",
"Aryan",
"Aryan\'s",
"Aryans",
"As",
"Asama",
"Asama\'s",
"Ascella",
"Ascella\'s",
"Asgard",
"Ashanti",
"Ashcroft",
"Ashe",
"Ashikaga",
"Ashikaga\'s"],'worddict': {'Ameslan': 561,
'Alnilam\'s': 445,
'Anton\'s': 761,
'Annabel': 709,
'Almoravid\'s': 443,
'Apalachicola': 782,
'Aldrin\'s': 328,
'Alistair\'s': 407,
'Ashikaga\'s': 1000,
'Abbas': 23,
'Arron\'s': 971,
'Aquinas\'s': 819,
'Annette\'s': 721,
'Alana\'s': 276,
'Annette': 720,
'Alana': 275,
'Arizona\'s': 915,
'Agamemnon\'s': 193,
'Arkansas\'s': 927,
'Arnulfo': 965,
'Aldo\'s': 326,
'Angelina': 660,
'Aguirre\'s': 218,
'Angeline': 662,
'Amur\'s': 587,
'Alabama\'s': 260,
'Alden': 322,
'Ahmadinejad\'s': 227,
'Aquinas': 818,
'Antipas': 753,
'Amaterasu': 524,
'Artie': 981,
'Algerian\'s': 371,
'Alcmena': 312,
'Antwerp': 774,
'Arturo': 983,
'Anubis\'s': 777,
'Altiplano': 484,
'Angie\'s': 674,
'Airedales': 242,
'Adolfo\'s': 133,
'Arnulfo\'s': 966,
'Afghan\'s': 172,
'Angus': 696,
'Arbitron': 860,
'Alaska': 280,
'Arcturus\'s': 875,
'Arizonian\'s': 920,
'Abe\'s': 32,
'Arcadian\'s': 865,
'Accra': 67,
'Armagnac': 938,
'Ampere': 579,
'Alfonzo\'s': 358,
'Albania\'s': 287,
'Airedale': 240,
'Abram': 50,
'Ana': 592,
'Angelou': 670,
'Anglophile': 685,
'America\'s': 538,
'Arabs': 837,
'Alex\'s': 346,
'Americanism\'s': 544,
'AC\'s': 5,
'Ararat\'s': 854,
'Amharic\'s': 564,
'Aristotle\'s': 910,
'Abelson': 36,
'Arnhem': 961,
'Allegheny': 417,
'Adhara\'s': 120,
'Antietam': 745,
'Antigua\'s': 749,
'Allentown': 423,
'Alford\'s': 360,
'Acheson\'s': 77,
'Andropov': 648,
'Alfonso\'s': 356,
'Amritsar': 581,
'Amie\'s': 567,
'Allie\'s': 425,
'Anne': 719,
'Abbott\'s': 26,
'Ajax\'s': 245,
'Apr\'s': 807,
'Aline': 394,
'Adventist\'s': 149,
'Alfonzo': 357,
'Ampere\'s': 580,
'Aristophanes\'s': 906,
'Arianism\'s': 896,
'Alan': 273,
'Aramaic': 847,
'Apollo\'s': 792,
'Alar': 277,
'Antares': 739,
'Araceli': 839,
'Aglaia': 201,
'Altai\'s': 477,
'Alexei': 352,
'Antichrists': 744,
'Acevedo': 69,
'Artemis\'s': 977,
'Almighty\'s': 439,
'Anselmo\'s': 729,
'Alzheimer\'s': 510,
'Amerindian': 557,
'Armani': 944,
'Ag\'s': 191,
'Aladdin\'s': 268,
'Adriatic\'s': 143,
'Aquafresh\'s': 813,
'Amanda': 519,
'Algerians': 372,
'AWOL\'s': 16,
'Armand': 940,
'Aquino': 820,
'AIDS\'s': 8,
'Absalom': 53,
'Addie\'s': 106,
'Alvaro': 499,
'Andre': 629,
'Aimee': 237,
'Aguinaldo': 215,
'Adrienne\'s': 145,
'Amerasian': 536,
'Arabic': 835,
'Alsatian': 469,
'Amber\'s': 531,
'Aeroflot': 163,
'Arawakan\'s': 859,
'Amtrak': 584,
'Alfreda\'s': 363,
'Agni\'s': 206,
'Arlene\'s': 931,
'Aeneid': 159,
'Alyson': 505,
'Algieba\'s': 374,
'Americanize': 549,
'Alvarez': 497,
'Alberto': 299,
'Aries': 898,
'Alberta': 297,
'Armstrong': 957,
'Antonia\'s': 765,
'Araceli\'s': 840,
'Algiers\'s': 376,
'Analects': 602,
'Antananarivo\'s': 734,
'Altai': 476,
'Ahriman\'s': 231,
'Allahabad': 412,
'Akron': 254,
'Abram\'s': 51,
'Achernar': 75,
'Adler': 129,
'Arabian': 832,
'Adirondacks': 125,
'Amiga\'s': 569,
'Anabaptist': 594,
'Almaty\'s': 437,
'Ashe': 998,
'Alaska\'s': 281,
'Argo': 885,
'Antilles\'s': 751,
'Abner\'s': 47,
'Altamira': 481,
'Aquarius\'s': 815,
'Apache': 779,
'American': 539,
'Akhmatova\'s': 248,
'Albireo': 303,
'Alioth\'s': 397,
'Alicia\'s': 391,
'Aden': 116,
'Adonis\'s': 137,
'Algieba': 373,
'Albion': 302,
'Andy\'s': 650,
'Appaloosa': 799,
'Adidas': 121,
'Ananias\'s': 605,
'Adolfo': 132,
'Aleutian\'s': 344,
'Android\'s': 644,
'Americanism': 543,
'Abner': 46,
'Aeolus': 161,
'Afro': 186,
'ASCII\'s': 12,
'Alcatraz': 307,
'Aquino\'s': 821,
'Armonk\'s': 954,
'Angeline\'s': 663,
'Abe': 31,
'Arius': 911,
'Annapolis': 715,
'Alison\'s': 403,
'Antares\'s': 740,
'Albany\'s': 292,
'Alistair': 406,
'Aldo': 325,
'Almighty': 438,
'Abelson\'s': 37,
'Aryan\'s': 988,
'Acropolis': 84,
'Anshan\'s': 731,
'Aaliyah\'s': 21,
'Antipas\'s': 754,
'Angolans': 690,
'Agricola': 208,
'Alger': 367,
'Arabian\'s': 833,
'Arthur\'s': 979,
'Ankara\'s': 705,
'Aaliyah': 20,
'Adriana\'s': 141,
'Amati': 526,
'Alsace': 467,
'Angolan\'s': 689,
'Aquitaine\'s': 823,
'ABM\'s': 4,
'Aileen': 235,
'Analects\'s': 603,
'A': 0,
'Adenauer': 118,
'Andrea\'s': 632,
'Alphonso\'s': 461,
'Aida\'s': 233,
'Advent': 146,
'Amerinds': 560,
'Alexis': 354,
'Amparo\'s': 578,
'Arcadia\'s': 863,
'Andalusia\'s': 618,
'AI\'s': 7,
'Adeline\'s': 115,
'Argonaut': 886,
'Albee': 293,
'Algonquian': 379,
'Alleghenies': 415,
'Artaxerxes\'s': 975,
'Aristides': 904,
'Aiken': 234,
'Anglicanism\'s': 680,
'Ali': 387,
'Aprils': 810,
'Anglicanism': 679,
'Allende': 421,
'Ala': 258,
'Agassiz': 196,
'Ana\'s': 593,
'ATM\'s': 14,
'Alphonso': 460,
'Afrikaner': 183,
'Anouilh': 726,
'Altaic': 478,
'Adderley': 103,
'Apollinaire': 790,
'Armenians': 950,
'Arequipa': 877,
'Agrippina': 211,
'Africans': 180,
'Antananarivo': 733,
'Appalachia': 795,
'Alkaid': 408,
'Arawakan': 858,
'Apocrypha': 788,
'Abyssinia': 55,
'Asgard': 995,
'Amarillo': 521,
'Afros': 189,
'Alisha\'s': 401,
'Acadia\'s': 62,
'Abbott': 25,
'Addams': 102,
'Alabamians': 266,
'Arabic\'s': 836,
'Adelaide\'s': 111,
'AOL': 10,
'Andrei\'s': 634,
'Aesop': 169,
'Adkins': 127,
'Aniakchak\'s': 699,
'Afrocentrism': 188,
'Antonio\'s': 768,
'Achilles': 78,
'Anshan': 730,
'Andorra\'s': 628,
'Aleppo\'s': 340,
'Araby': 838,
'Amenhotep\'s': 535,
'Argentinians': 884,
'Akron\'s': 255,
'Adar': 100,
'Americanizing': 552,
'Arron': 970,
'Accra\'s': 68,
'Aquila': 817,
'Adam': 94,
'Adan': 97,
'Antichrist': 742,
'Araucanian': 855,
'Anglicanisms': 681,
'Alsatian\'s': 470,
'Alcibiades': 309,
'Amado\'s': 516,
'Aguilar\'s': 214,
'Anacin': 598,
'Angelina\'s': 661,
'Arturo\'s': 984,
'Aaron': 22,
'Abidjan': 42,
'Amiga': 568,
'Arbitron\'s': 861,
'Accenture': 65,
'Abel': 33,
'Alvin\'s': 502,
'Amerind': 555,
'Angoras': 693,
'Afghans': 175,
'Aphrodite': 785,
'Advil': 151,
'Arizonan': 916,
'Antoine': 757,
'Aegean\'s': 154,
'A\'s': 1,
'Allan\'s': 414,
'Adderley\'s': 104,
'Alma': 432,
'Accenture\'s': 66,
'Armando': 942,
'Andromeda': 646,
'Alexander\'s': 348,
'Aniakchak': 698,
'Antone': 762,
'Adolph': 134,
'Arafat\'s': 842,
'Alphecca': 454,
'Alaskan': 282,
'Anchorage': 615,
'Alpine': 462,
'Ascella\'s': 994,
'Anacin\'s': 599,
'Annmarie': 724,
'Ahab': 221,
'Acapulco\'s': 64,
'Aisha': 243,
'Alford': 359,
'Alcoa': 314,
'Americanization': 546,
'Ashcroft': 997,
'Aeneas': 157,
'Alva': 494,
'Artemis': 976,
'Allen': 420,
'Appalachians': 798,
'Aron': 967,
'Agnew': 203,
'Anasazi': 606,
'Anita': 702,
'Agnes': 202,
'Angola': 686,
'Adele\'s': 113,
'Angelia': 656,
'Americanizes': 551,
'Apr': 806,
'Adirondacks\'s': 126,
'Alphecca\'s': 455,
'Arius\'s': 912,
'Americanized': 550,
'Alps\'s': 466,
'Arrhenius': 969,
'Antarctic': 735,
'Ahmadinejad': 226,
'Aldrin': 327,
'Adelaide': 110,
'Acheson': 76,
'Anatolia': 610,
'Adolf': 130,
'Aldebaran\'s': 321,
'Aguirre': 217,
'Amur': 586,
'Antarctica\'s': 738,
'Alberta\'s': 298,
'Arianism': 895,
'Anthony': 741,
'Antony': 770,
'Aladdin': 267,
'Algeria': 368,
'Anacreon': 600,
'Alhambra': 384,
'Andrianampoinimerina\'s': 642,
'Argos': 890,
'Altman': 486,
'Angevin': 671,
'Amsterdam\'s': 583,
'Armageddon\'s': 936,
'Africa\'s': 177,
'Andretti\'s': 637,
'Afghan': 171,
'Alexander': 347,
'Archie': 869,
'Ahmed': 228,
'Arizonan\'s': 917,
'Aryan': 987,
'Albanians': 290,
'Adkins\'s': 128,
'Argonaut\'s': 887,
'Annabel\'s': 710,
'Angevin\'s': 672,
'Algol': 377,
'Arizonians': 921,
'Apple': 801,
'Aristarchus': 902,
'Armstrong\'s': 958,
'Arjuna': 922,
'Alaskan\'s': 283,
'Archibald': 867,
'Allah': 410,
'Adonises': 138,
'Allan': 413,
'Adela': 108,
'Akita': 250,
'Andalusian': 619,
'Adele': 112,
'Aphrodite\'s': 786,
'Amelia\'s': 533,
'Armour\'s': 956,
'Akbar': 246,
'Alpert': 450,
'Alejandra': 333,
'Angelo': 668,
'Adirondack\'s': 124,
'Alcyone': 318,
'Abilene': 45,
'Archibald\'s': 868,
'Anton': 760,
'Angela': 654,
'Aristotelian': 907,
'Ara\'s': 827,
'Alighieri': 392,
'Arneb\'s': 960,
'Alton': 490,
'Adeline': 114,
'Advents': 150,
'Alicia': 390,
'Albert': 296,
'Addie': 105,
'Arab': 828,
'Araguaya\'s': 844,
'Alec\'s': 330,
'Antioch': 752,
'Alderamin': 323,
'Aggie': 200,
'AM\'s': 9,
'Ascella': 993,
'Aral': 845,
'Adan\'s': 98,
'Americanisms': 545,
'Algerian': 370,
'Antichrist\'s': 743,
'Alvaro\'s': 500,
'Angelita\'s': 667,
'Algonquians': 381,
'Almach': 434,
'Abidjan\'s': 43,
'African\'s': 179,
'Allison': 426,
'Althea': 482,
'Altoids': 488,
'Algol\'s': 378,
'Alioth': 396,
'Alabama': 259,
'Abraham': 48,
'Arapaho': 851,
'Angelique': 664,
'Andrianampoinimerina': 641,
'Appalachian': 797,
'Alston': 473,
'ASL\'s': 13,
'Alphonse': 458,
'Ariadne\'s': 894,
'Apocrypha\'s': 789,
'Ashikaga': 999,
'Ashanti': 996,
'Arminius': 951,
'Antarctica': 737,
'Afrikaner\'s': 184,
'Amsterdam': 582,
'Armageddon': 935,
'Alyson\'s': 506,
'Akihito': 249,
'Art\'s': 973,
'Appleseed': 803,
'Antofagasta\'s': 756,
'Anglicans': 682,
'Arab\'s': 829,
'Abdul': 29,
'Acts': 89,
'AA\'s': 2,
'Allison\'s': 427,
'AZ\'s': 17,
'Alvarado': 495,
'Alberio\'s': 295,
'Abuja': 54,
'Anna': 708,
'Aeschylus\'s': 166,
'Alton\'s': 491,
'As': 990,
'Adolf\'s': 131,
'Arline\'s': 933,
'Antwan\'s': 773,
'Achilles\'s': 79,
'Agatha\'s': 199,
'Anglo': 684,
'Arawak': 856,
'Aryans': 989,
'Albireo\'s': 304,
'Aquitaine': 822,
'Alphard': 452,
'Altoids\'s': 489,
'Arlington': 934,
'Allstate': 428,
'Argus\'s': 892,
'Alsop': 471,
'Apia': 787,
'ACTH\'s': 6,
'Alaric': 279,
'Amie': 566,
'Albanian': 288,
'Amy\'s': 591,
'Ahmad': 223,
'Ahmed\'s': 229,
'Archimedes': 871,
'Alcuin': 317,
'Adriana': 140,
'Arkansan\'s': 925,
'Aramaic\'s': 848,
'Acuff\'s': 91,
'Aludra': 492,
'Allegra': 418,
'Afrikaans': 181,
'Allstate\'s': 429,
'Angel': 652,
'Ar\'s': 825,
'Araguaya': 843,
'Aludra\'s': 493,
'Alamo\'s': 270,
'Amharic': 563,
'Adela\'s': 109,
'Appaloosa\'s': 800,
'Anatole': 608,
'Armagnac\'s': 939,
'Angelia\'s': 657,
'Antoine\'s': 758,
'Abyssinian': 57,
'Angelique\'s': 665,
'Arizonans': 918,
'Alabamian': 264,
'Afghanistan': 173,
'Argentinian\'s': 883,
'Adrienne': 144,
'Adam\'s': 95,
'Amoco\'s': 575,
'Anselmo': 728,
'Antonius': 769,
'Arizonian': 919,
'Anaxagoras': 614,
'Anderson': 624,
'Ann\'s': 707,
'Akiva\'s': 252,
'Aleutian': 343,
'Angus\'s': 697,
'Amman': 572,
'AB\'s': 3,
'Android': 643,
'Achebe': 73,
'Angkor': 675,
'Appleton': 804,
'Ada\'s': 93,
'Aleichem': 331,
'Americanizations': 548,
'Alejandro': 335,
'Acuff': 90,
'Alembert\'s': 338,
'Amalia\'s': 518,
'Argentinian': 882,
'Alabaman': 261,
'Aelfric\'s': 156,
'Alcoa\'s': 315,
'Altman\'s': 487,
'Aeolus\'s': 162,
'Aron\'s': 968,
'Appalachia\'s': 796,
'Alice\'s': 389,
'Akhmatova': 247,
'Aeneas\'s': 158,
'Americana\'s': 542,
'Andretti': 636,
'Addison': 107,
'American\'s': 540,
'Aristophanes': 905,
'Aguinaldo\'s': 216,
'Anglican\'s': 678,
'Argus': 891,
'Arlene': 930,
'Aline\'s': 395,
'AOL\'s': 11,
'Aleut': 341,
'African': 178,
'Algenib': 365,
'Arno': 962,
'Altaic\'s': 479,
'ATP\'s': 15,
'Angola\'s': 687,
'Antwerp\'s': 775,
'Aegean': 153,
'Algenib\'s': 366,
'Angora\'s': 692,
'Andrew\'s': 639,
'Arthur': 978,
'Agassiz\'s': 197,
'Archie\'s': 870,
'Apollonian': 793,
'Amerind\'s': 556,
'Algonquin': 382,
'Abernathy': 40,
'Aconcagua\'s': 81,
'Agrippina\'s': 212,
'Aleichem\'s': 332,
'Aberdeen': 38,
'Apollos': 794,
'Annie': 722,
'Abelard': 35,
'Alcindor': 310,
'Ahab\'s': 222,
'Andorra': 627,
'Aleppo': 339,
'Angel\'s': 653,
'Alpo\'s': 464,
'Americanization\'s': 547,
'Antoninus': 766,
'Alcott': 316,
'Alhena\'s': 386,
'Acrux\'s': 86,
'Alsop\'s': 472,
'Amaru': 522,
'Arctic': 872,
'Anatolia\'s': 611,
'Alyssa': 507,
'Ajax': 244,
'Adriatic': 142,
'Acrux': 85,
'Agustin': 219,
'Armenian': 948,
'Alhena': 385,
'Annmarie\'s': 725,
'Anatolian': 612,
'Amway': 588,
'Adventist': 148,
'Althea\'s': 483,
'Algiers': 375,
'Abraham\'s': 49,
'Adams': 96,
'Arafat': 841,
'Armenian\'s': 949,
'Ahmad\'s': 224,
'Annapurna\'s': 718,
'Angolan': 688,
'Anaheim': 601,
'Antilles': 750,
'Agatha': 198,
'Aelfric': 155,
'Alisa': 398,
'Alpheratz': 456,
'Alexandra': 349,
'Alighieri\'s': 393,
'Anglican': 677,
'Anabel\'s': 597,
'Asama\'s': 992,
'Achaean\'s': 72,
'Afrikaners': 185,
'Argentina\'s': 880,
'Alejandra\'s': 334,
'Ann': 706,
'Amman\'s': 573,
'Alderamin\'s': 324,
'Alfonso': 355,
'Amerindians': 559,
'Angie': 673,
'Amish\'s': 571,
'Allie': 424,
'Andes\'s': 626,
'Alpheratz\'s': 457,
'Agassi': 194,
'Albanian\'s': 289,
'Alnitak\'s': 447,
'Agrippa': 209,
'Alpert\'s': 451,
'Alejandro\'s': 336,
'Ariz': 913,
'April\'s': 809,
'Am\'s': 512,
'Ares': 878,
'Anguilla': 694,
'Alyce': 503,
'Armonk': 953,
'Abrams': 52,
'Artie\'s': 982,
'Armenia\'s': 947,
'Antwan': 772,
'Arden': 876,
'Aristotelian\'s': 908,
'Alphard\'s': 453,
'Alkaid\'s': 409,
'Alcestis': 308,
'Angelita': 666,
'Amaru\'s': 523,
'Arctic\'s': 873,
'Alisha': 400,
'Amelia': 532,
'Argonne\'s': 889,
'Alabamian\'s': 265,
'Allyson\'s': 431,
'Alisa\'s': 399,
'America': 537,
'Acapulco': 63,
'Allyson': 430,
'Arkhangelsk': 928,
'Anatole\'s': 609,
'Alan\'s': 274,
'Arieses': 900,
'Arabia': 830,
'Aleut\'s': 342,
'Aeroflot\'s': 164,
'Almohad\'s': 441,
'Aachen': 19,
'Ariadne': 893,
'Amway\'s': 589,
'Archean': 866,
'Anabaptist\'s': 595,
'Arkwright': 929,
'Amazon': 527,
'Anubis': 776,
'Aida': 232,
'Amadeus\'s': 514,
'Andres': 635,
'Angelica': 658,
'Arline': 932,
'Albany': 291,
'Aesculapius\'s': 168,
'Antigua': 748,
'Abyssinian\'s': 58,
'Alonzo': 448,
'Alabamans': 263,
'Abyssinia\'s': 56,
'Allah\'s': 411,
'Anabel': 596,
'Apuleius': 811,
'Argentina': 879,
'Armando\'s': 943,
'Afghanistan\'s': 174,
'Amaterasu\'s': 525,
'Abernathy\'s': 41,
'Antony\'s': 771,
'Aldebaran': 320,
'Aquarius': 814,
'Alonzo\'s': 449,
'Aristarchus\'s': 903,
'Apalachicola\'s': 783,
'Angelo\'s': 669,
'Ariel': 897,
'Acadia': 61,
'Amparo': 577,
'Ahmadabad': 225,
'Aconcagua': 80,
'Angora': 691,
'Andalusia': 617,
'Anselm': 727,
'Andrews': 640,
'Ariosto': 901,
'Anibal': 700,
'Alice': 388,
'Alta': 475,
'Alamo': 269,
'Alexandria': 350,
'Amoco': 574,
'Advil\'s': 152,
'Adhara': 119,
'Amazon\'s': 528,
'Andromeda\'s': 647,
'Alvarez\'s': 498,
'Albania': 286,
'Art': 972,
'Anchorage\'s': 616,
'Alamogordo': 271,
'Armour': 955,
'Aden\'s': 117,
'Alissa': 404,
'Ara': 826,
'Aristotle': 909,
'Alleghenies\'s': 416,
'Ark': 923,
'Alamogordo\'s': 272,
'Agra': 207,
'Ainu': 239,
'Actaeon': 87,
'Antarctic\'s': 736,
'Apache\'s': 780,
'Aruba': 985,
'Aral\'s': 846,
'Amado': 515,
'Alberio': 294,
'Arneb': 959,
'Acton': 88,
'Allende\'s': 422,
'Andy': 649,
'Alfred': 361,
'Altiplano\'s': 485,
'Alma\'s': 433,
'Aramco\'s': 850,
'Annie\'s': 723,
'Alnilam': 444,
'Abbasid': 24,
'Arno\'s': 963,
'Annam': 713,
'Agni': 205,
'Angara': 651,
'Albuquerque': 305,
'Annabelle': 711,
'Alexandria\'s': 351,
'Alzheimer': 509,
'Anatolian\'s': 613,
'Armenia': 946,
'Annabelle\'s': 712,
'Albuquerque\'s': 306,
'Apollo': 791,
'Antigone': 746,
'Abby': 27,
'Antaeus': 732,
'Antonia': 764,
'Arcadia': 862,
'Arabia\'s': 831,
'Alberto\'s': 300,
'Aguilar': 213,
'Albigensian': 301,
'Alphonse\'s': 459,
'Antonio': 767,
'Alembert': 337,
'Andes': 625,
'Annam\'s': 714,
'Apennines': 784,
'Andre\'s': 630,
'Abdul\'s': 30,
'Arawak\'s': 857,
'Alcmena\'s': 313,
'Aesculapius': 167,
'Alcindor\'s': 311,
'Amber': 530,
'Alvin': 501,
'Agnew\'s': 204,
'Americana': 541,
'Abby\'s': 28,
'Alyce\'s': 504,
'Akiva': 251,
'Amalia': 517,
'Aries\'s': 899,
'Americans': 553,
'Amherst': 565,
'Ananias': 604,
'Adolph\'s': 135,
'Antoinette': 759,
'Allegra\'s': 419,
'Algonquian\'s': 380,
'Andersen': 622,
'Alvarado\'s': 496,
'Antofagasta': 755,
'Alyssa\'s': 508,
'Arkansan': 924,
'Angelico': 659,
'Altair': 480,
'Adana': 99,
'Arkansas': 926,
'Ada': 92,
'Appomattox': 805,
'Armand\'s': 941,
'Alexei\'s': 353,
'Agustin\'s': 220,
'Almoravid': 442,
'Alar\'s': 278,
'Aldan': 319,
'Alissa\'s': 405,
'Acosta': 82,
'Anibal\'s': 701,
'Amy': 590,
'Antigone\'s': 747,
'Adirondack': 123,
'Aesop\'s': 170,
'Algeria\'s': 369,
'Adar\'s': 101,
'Alabaman\'s': 262,
'Alps': 465,
'Anguilla\'s': 695,
'Arabians': 834,
'Amanda\'s': 520,
'Arizona': 914,
'Abel\'s': 34,
'Algonquin\'s': 383,
'Amerindian\'s': 558,
'Ac\'s': 60,
'Anastasia': 607,
'Anita\'s': 703,
'Alaskans': 284,
'Adrian': 139,
'Alpo': 463,
'Artaxerxes': 974,
'Asama': 991,
'Aramco': 849,
'Almach\'s': 435,
'Anzac': 778,
'Aimee\'s': 238,
'Amenhotep': 534,
'Amazons': 529,
'Akkad': 253,
'Acosta\'s': 83,
'Africa': 176,
'Airedale\'s': 241,
'Anglicize': 683,
'Alston\'s': 474,
'Annapolis\'s': 716,
'Antone\'s': 763,
'Argentine': 881,
'Angela\'s': 655,
'Amundsen': 585,
'Alison': 402,
'Anglia': 676,
'Argonne': 888,
'Arapaho\'s': 852,
'Afro\'s': 187,
'Achebe\'s': 74,
'Aruba\'s': 986,
'Apaches': 781,
'Ameslan\'s': 562,
'Abigail': 44,
'Aquafresh': 812,
'Andaman': 620,
'Ararat': 853,
'AZT\'s': 18,
'Aeneid\'s': 160,
'Alnitak': 446,
'Agrippa\'s': 210,
'Acevedo\'s': 70,
'Armageddons': 937,
'Almohad': 440,
'Apple\'s': 802,
'Ahriman': 230,
'Andrew': 638,
'Adonis': 136,
'Aquariuses': 816,
'Ankara': 704,
'Annapurna': 717,
'Arminius\'s': 952,
'Andrei': 633,
'Amadeus': 513,
'Andrea': 631,
'Arthurian': 980,
'Agassi\'s': 195,
'Alsace\'s': 468,
'Adidas\'s': 122,
'Alex': 345,
'Achaean': 71,
'Al\'s': 257,
'Aberdeen\'s': 39,
'Arnold': 964,
'April': 808,
'Arcadian': 864,
'Andersen\'s': 623,
'Alfreda': 362,
'Alfredo': 364,
'Advent\'s': 147,
'Almaty': 436,
'Americas': 554,
'Amos': 576,
'Alec': 329,
'Andromache': 645,
'Arcturus': 874,
'Ac': 59,
'Amish': 570,
'Agamemnon': 192,
'Ag': 190,
'Andean': 621,
'Alba': 285,
'Aileen\'s': 236,
'Am': 511,
'Al': 256,
'Armani\'s': 945,
'Aeschylus': 165,
'Ar': 824,
'Afrikaans\'s': 182,
}
}
